### PR TITLE
tune glibc memory allocation and make it better suited for Java processes

### PR DESCRIPTION
**Pull request by lhotari**
- MALLOC_ARENA_MAX is explained in https://devcenter.heroku.com/articles/tuning-glibc-memory-behavior#what-value-to-choose-for-malloc_arena_max
or https://www.ibm.com/developerworks/community/blogs/kevgrig/entry/linux_glibc_2_10_rhel_6_malloc_may_show_excessive_virtual_memory_usage?lang=en

It saves memory especially on 64-bit JVM processes. Search for MALLOC_ARENA_MAX on Google, SO or Github to find others using it.

I'm not sure if this file `ci_environment/java/files/default/etc/profile.d/malloc_tune.sh` is the proper place for doing this setting.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
It is not clear to me how setting this default for all users is preferable. Each user can alter this setting, and changing the default seems counterintuitive.

**Comment by lhotari** [comment]
@BanzaiMan I believe it's worth setting a default for MALLOC_ARENA_MAX since it reduces the memory allocation overhead especially in 64-bit environments. If someone whats to use a different value they can always set the environment variable in their `.travis.yml` file. 

It's not only Java processes that benefit from setting MALLOC_ARENA_MAX to a low value. [Here's an example of ruby](https://github.com/mperham/sidekiq/issues/2070).

The [slide number 7 in Kevin Grigorenko's presentation](http://www-01.ibm.com/support/docview.wss?uid=swg27039764&aid=1#page=7) explains what MALLOC_ARENA_MAX setting is about.

Another blog post explaining MALLOC_ARENA_MAX : https://www.infobright.com/index.php/malloc_arena_max

**Comment by joshk** [comment]
@lhotari have you run this against some of your builds to see if there is any improvement in ram usage?

**Comment by BanzaiMan** [comment]
@lhotari Hi, we'd like to decide whether or not we should include this in this week's environment update. Could you answer @johsk's question above? Thank you!

**Comment by lhotari** [comment]
@joshk @BanzaiMan 
There is more data from Heroku about how MALLOC_ARENA_MAX reduces memory usage. See the report at https://devcenter.heroku.com/articles/testing-cedar-14-memory-use .

The [setting is used for Grails builds](https://github.com/grails/grails-core/blob/8bc444592adf80ce7b66391f05d98d06f8c5db13/.travis.yml#L7), but I haven't done actual measurements on Travis.

**Comment by BanzaiMan** [comment]
@lhotari Thank you! I've pinged other users reporting memory issues. I will incorporated this to the next week's update if it goes well.

**Comment by lhotari** [comment]
@BanzaiMan I added another commit that disables dynamic mmap threshold in malloc. Disabling that can help reduce heap fragmentation.

**Pull request merged**
