### PR TITLE
Getting rid of obsolete stuff & duplicate cookbooks

### PR DESCRIPTION
**Pull request by meatballhat**

### CODE REVIEW

**Comment by alex** [comment]
I glanced at files with `python` in their name. I don't really have a way to evaluate the correctness of this PR is what I established.

**Comment by meatballhat** [comment]
@alex correctness evaluation not necessary :smiley: I mostly wanted to make sure you're aware of what's happening in `master` :sparkling_heart:

**Comment by tianon** [comment]
maaaasive :+1:

**Comment by ljharb** [comment]
I can't claim to understand what this PR is doing - if there's relevant lines I should look at please let me know :-)

**Comment by meatballhat** [comment]
@ljharb my intent is for you to not be negatively affected in any way :smiley:  Sorry for the PR spam.  I wanted to make sure yinz were aware of change since you've been recent contributors.

**Pull request merged**
