### PR TITLE
updates for riak 2.0 ubuntu/deb

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
Solves https://github.com/travis-ci/travis-ci/issues/2866.

I've tested this running ubuntu/precise64 via virtualbox/vagrant. The tests pass for the java 1.4.4 riak-java-client, https://github.com/basho/riak-java-client/tree/1.4.4, and the 2.0 spec tests from the riak-ruby-client, https://github.com/basho/riak-ruby-client.

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
@BanzaiMan, here's some notes. Let me know if they suffice.

- - -

## [When Downgrading is No Longer an Option](http://docs.basho.com/riak/latest/upgrade-v20/#When-Downgrading-is-No-Longer-an-Option)

> If you decide to upgrade to version 2.0, you can still downgrade your cluster to an earlier version of Riak if you wish, **unless** you perform one of the following actions in your cluster:

> * **Index data to be used in conjunction with the new [Riak Search](http://docs.basho.com/riak/latest/dev/using/search/)**.

> * **Create and activate one or more bucket types**. By extension, you will not be able to downgrade your cluster if you have used the following features, both of which rely on bucket types:
    * **[Strong consistency](http://docs.basho.com/riak/latest/theory/concepts/strong-consistency/)**
    * **[Riak Data Types](http://docs.basho.com/riak/latest/dev/using/data-types/)**

> If you use other new features, such as [Riak Security](http://docs.basho.com/riak/latest/ops/running/authz/) or the new [configuration files](http://docs.basho.com/riak/latest/ops/advanced/configs/configuration-files/), you can still downgrade your cluster, but you will no longer be able to use those features after the downgrade.

**Note**: [As per Riak's 2.0 downgrade notes](https://github.com/basho/riak/wiki/2.0-downgrade-notes), a warning is issued by the `riak-admin` command used to create and activate bucket types, in order to notify the database operators of the irreversible nature of activation. Also, when making use of the [Bitcask](http://docs.basho.com/riak/latest/ops/advanced/backends/bitcask/) backend, please take a look at this [downgrade section](https://github.com/basho/riak/wiki/2.0-downgrade-notes#bitcask-downgrades).

If not you're not relying on Riak 2.0's bucket types or indexing data in conjunction with Riak Search, you can approach downgrading via [**rolling downgrades**](http://docs.basho.com/riak/latest/ops/upgrading/rolling-downgrades/).

## [Using Older Riak Clients](http://docs.basho.com/riak/latest/upgrade-v20/#New-Clients)

> While we strongly recommend using the newest versions of these clients, older versions will still work with Riak 2.0, with the drawback that those older clients will not able to take advantage of new features like data types or the new Riak Search.

## [Upgrading to 2.0](http://docs.basho.com/riak/latest/upgrade-v20/)

Please take a look at the [docs](http://docs.basho.com/riak/latest/intro-v20/) for more information about Riak 2.0's new features and updated [clients](http://docs.basho.com/riak/latest/upgrade-v20/#New-Clients).

- - -

**Comment by zeeshanlakhani** [comment]
Thanks @BanzaiMan.

**Comment by BanzaiMan** [comment]
I'm testing this cookbook again, and now it's failing.

https://packagecloud.io/basho/riak/ubuntu/ is now returning 404. Looks like it's moved one directory up to https://packagecloud.io/basho/riak/.

**Comment by BanzaiMan** [comment]
https://packagecloud.io/basho/riak/ isn't right, either.

```
    ================================================================================
    Error executing action `add` on resource 'apt_repository[basho-riak]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    execute[update package index] (/tmp/vm-provisioning/travis-cookbooks/ci_environment/apt/providers/repository.rb line 57) had an error: Mixlib::ShellOut::ShellCommandFailed: E
xpected process to exit with [0], but received '100'
    ---- Begin output of apt-get update ----
    STDOUT: 
    STDERR: E: The method driver /usr/lib/apt/methods/https could not be found.
    ---- End output of apt-get update ----
    Ran apt-get update returned 100
    
    Cookbook Trace:
    ---------------
    /tmp/vm-provisioning/travis-cookbooks/ci_environment/apt/providers/repository.rb:60:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /tmp/vm-provisioning/travis-cookbooks/ci_environment/riak/recipes/default.rb
    
      4: apt_repository 'basho-riak' do
      5:   uri          'https://packagecloud.io/basho/riak/'
      6:   distribution node["lsb"]["codename"]
      7:   components   ["main"]
      8:   key          'https://packagecloud.io/gpg.key'
      9: 
     10:   action :add
     11: end
     12: 
```

**Comment by zeeshanlakhani** [comment]
I think this was due to the recent update in the 2.x.x series, to 2.0.4. I'm checking in w/ the Riak Release Eng. and will have an update on what will be constant.

**Comment by zeeshanlakhani** [comment]
So, for one the thing, `https://packagecloud.io/basho/riak/ubuntu/ ` should be the uri and will return a 404 in the browser. Other examples of packagecloud links work the same way, e.g. https://github.com/cybem/graphite-api-iow/blob/e3cdea556cbaf9853595b9d65b9fd9c8b9473be4/docs/installation.rst#debian--ubuntu-native-package, https://github.com/opsmatic/opsmatic-cookbook/blob/312c1d6ea70e1833f7cb971588b36a178145d736/recipes/debian_public.rb.

Hmm... via my local travis-ci-cookbook Vagrant Instance (up to date w/ master), using a simplified vagrantfile for the needs pertaining to riak, I'm able to get 2.0.4 running. 

screen shot 2015-01-14 at 2 50 22 pm

**Comment by zeeshanlakhani** [comment]
@BanzaiMan, can you send me logs that would pertain to the failure for the `https://packagecloud.io/basho/riak/ubuntu/` uri?

**Comment by zeeshanlakhani** [comment]
@BanzaiMan, 

So... I ran-up my instance a few times w/ `https://packagecloud.io/basho/riak/ubuntu/` as the uri, and it's working (again, w/ my minimal V.file). Definitely, send me any failures you get w/ the above uri.

screen shot 2015-01-14 at 7 00 46 pm

**Comment by BanzaiMan** [comment]
It fails the same way as above. In fact, after this cookbook runs, any attempt to run `apt-get` fails. `/etc/apt/sources.list.d/basho-riak-source.list` must be removed once this cookbook runs.

**Comment by zeeshanlakhani** [comment]
@BanzaiMan, Ok, looking around the issue you posted, it seems related to, http://askubuntu.com/questions/165676/how-do-i-fix-a-e-the-method-driver-usr-lib-apt-methods-http-could-not-be-foun, which refers to the need for `apt-transport-https` (mentioned in https://packagecloud.io/basho/riak/install). Not sure why this changed, but would probably do the trick. Can you add that to the apt cookbook and see if you can fix it? Things still work for me here, locally. 

Thank you so much and sorry for the hassle.

**Comment by zeeshanlakhani** [comment]
@BanzaiMan, saw the commit for apt-transport-https go through, let me know if you have any luck. The uri should probably still point to .../ubuntu/. Thanks.

**Comment by BanzaiMan** [comment]
@zeeshanlakhani I tested this again with `…/ubuntu/`, and it worked. Not sure how it failed before, to be quite honest, but I'm OK with just rolling with it.

Thanks for your contribution!

**Comment by zeeshanlakhani** [comment]
@BanzaiMan great! Yeah... the need for https-transport is was sudden, but I'm glad it's working.

**Pull request merged**
