### PR TITLE
Switch go version management to gimme

### PR DESCRIPTION
**Pull request by meatballhat**

### CODE REVIEW

**Comment by meatballhat** [comment]
OH YEAH

screenshot 2015-01-30 18 16 08

**Comment by BanzaiMan** [comment]
Can we leave the `golang::multi` recipe in place? There might be build that depends on it. If we are removing it (to which I am not opposed), we should give some lead time.

**Comment by meatballhat** [comment]
Do you mean there might be builds outside of travis-cookbooks that depend
on it?  I'm fine with leaving both golang and gvm cookbooks in place,
perhaps with a deprecation warning?  I also tend to think that if there are
folks outside of Travis depending on these, they can always vendor or pin
at a git ref prior to deletion :smiley_cat:

**Comment by BanzaiMan** [comment]
I see a few of them in https://github.com/search?l=&p=4&q=gvm+filename%3A.travis.yml&ref=advsearch&type=Code&utf8=%E2%9C%93.

Some are just Groovy builds that wants to use their own `gvm`, but some seem to legitimately depend on `gvm`.

I'm :+1: on deprecation warning right now, and removing it entirely in the next update in 2 months.

**Comment by meatballhat** [comment]
Ah, so this is more about `gvm` being available?  If so, then we may have to opt for dealing with some temporary breakage, advising those who need/want `gvm` to either switch to using `gimme` or bootstrapping `gvm` themselves.  It doesn't make sense to me, but the mere presence of a `gvm` installation causes issues around `GOROOT` such that `go` becomes unusable unless managed by `gvm`, which is why the `travis-build` PR includes an `unset gvm` and moves the `~/.gvm` dir out of the way.  It's a lovely mess.

**Comment by BanzaiMan** [comment]
My inclination, then, is to postpone this to the next update, and add the deprecation warning now. Non-Go builds can still use `gvm`, so we would have to figure out how to do that.

**Pull request merged**
