### PR TITLE
Removed old php 5.2.17 definition file

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
There's still old stuff in php/attributes/default.rb btw.

**Comment by garex** [comment]
Why did you do thiis??? I can't translate it into English, but in Russian it's just one word — pizdec..

**Comment by josegonzalez** [comment]
@garex Not for nothing, but there isn't any need to be an asshole to these people.

They removed it because there is no way to compile php 5.2 at the moment on their infrastructure, and they made a business decision to upgrade the *rest* of php for now. In fact, in the other issue you commented on, they said they'd be willing to add it back if someone would figure out how to fix compilation. I'm sure they would merge in your changes that fix PHP 5.2 and re-add support for it.

Yeah, it's a pain in the ass if you're still supporting 5.2, but they are stuck between a rock and a hard place. I'd rather the rest of PHP gets updates on their infrastructure than be stuck because a version of PHP last supported 4 years ago can no longer be installed.

**Comment by garex** [comment]
@josegonzalez do we really need updates that just break production? I dont' think so.

I know, that Hiro @BanzaiMan tried to fix it, but does really updates worth of breaking stable builds?? I dont' think.

And about business. If I'm a client of a company that tells, that it support versions from A to Z, I'm sure it need to support it during my contract between me and company. If in future company decides to drop version from A to F it means that it will break contract with me.

Similar from OOP world — https://en.wikipedia.org/wiki/Liskov_substitution_principle

**Comment by garex** [comment]
@BanzaiMan in this non-stable situation does it's worth to use travis then? Or just create through docker my own builds, that dont' require updates and test at home?

**Pull request merged**
