### PR TITLE
Revert "Update virtualenv to 16.3.0"

### PR DESCRIPTION
**Pull request by DamianSzymanski**
Reverts travis-ci/travis-cookbooks#1065

### CODE REVIEW

**Comment by acjh** [comment]
@DamianSzymanski Can you share why you reverted the change?

**Comment by acjh** [comment]
@DamianSzymanski Can you share why you reverted the change?

**Comment by acjh** [comment]
@DamianSzymanski Can you share why you reverted the change?

**Comment by DamianSzymanski** [comment]
@acjh Sorry for late replay, packer build didn't work and we are going to move this to attribute
https://github.com/travis-ci/travis-cookbooks/blob/ubuntu-2004/cookbooks/travis_build_environment/recipes/virtualenv.rb#L5
We are about to release focal and new version is needed there

**Comment by acjh** [comment]
Where may I track that?

**Comment by DamianSzymanski** [comment]
In the packer builds history:
https://travis-ci.org/github/travis-infrastructure/packer-build/builds

**Comment by acjh** [comment]
Where is the new version of `virtualenv` set?

**Pull request merged**
