### PR TITLE
Add the "travis" user to the "docker" group

### PR DESCRIPTION
**Pull request by tianon**
This way, we can `docker` without `sudo`! :tada:

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Not sure if this would work as is. Might have to `include_recipe 'travis_build_environment'`. I might try that first.

**Comment by BanzaiMan** [comment]
```diff
commit eb14bc3de044e7eda8cc9f09f1746e47da181b18
Author: Hiro Asari <asari.ruby@gmail.com>
Date:   Thu Mar 12 22:18:44 2015 -0400

    Add build user to 'docker' group

diff --git a/ci_environment/docker/attributes/default.rb b/ci_environment/docker/attributes/default.rb
index 5abb062..2142bc3 100644
--- a/ci_environment/docker/attributes/default.rb
+++ b/ci_environment/docker/attributes/default.rb
@@ -1 +1,2 @@
-default['docker']['version'] = '1.5.0'
\ No newline at end of file
+default['docker']['version'] = '1.5.0'
+default['docker']['users'] = [ node.travis_build_environment.user ]
diff --git a/ci_environment/docker/recipes/default.rb b/ci_environment/docker/recipes/default.rb
index 62d2a6a..7e576a8 100644
--- a/ci_environment/docker/recipes/default.rb
+++ b/ci_environment/docker/recipes/default.rb
@@ -8,6 +8,7 @@
 #
 
 include_recipe 'apt'
+include_recipe 'travis_build_environment'
 
 apt_repository 'docker' do
   uri "https://get.docker.io/ubuntu"
```

**Comment by tianon** [comment]
:+1:, makes sense :heart:

**Comment by tianon** [comment]
You're going to either merge or PR https://github.com/travis-ci/travis-cookbooks/compare/ha-feature-trusty...ha-feature-docker-group, right? :smile:

**Comment by BanzaiMan** [comment]
Correct. :-)

**Comment by tianon** [comment]
:heart_eyes: :+1:

**Comment by BanzaiMan** [comment]
```
$ ssh travis@NNN.NNN.NNN.NNN -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
Warning: Permanently added 'NNN.NNN.NNN.NNN' (RSA) to the list of known hosts.
travis@NNN.NNN.NNN's password: 
Last login: Fri Mar 13 02:20:17 2015 from 64.149.142.214
travis@minimal-test:~$ docker run -i -t ubuntu /bin/date
Unable to find image 'ubuntu:latest' locally
511136ea3c5a: Pull complete 
511136ea3c5a: Download complete 
f0dde87450ec: Download complete 
76b658ecb564: Download complete 
4faa69f72743: Download complete 
2103b00b3fdf: Download complete 
Status: Downloaded newer image for ubuntu:latest
Fri Mar 13 02:44:29 UTC 2015
```

**Pull request closed without merging**
