### PR TITLE
Bump Python/nodejs/php/Firefox package versions

### PR DESCRIPTION
**Pull request by edmorley**
Many of these are overridden by the versions set in package-templates (which I'll update shortly), however seeing as they are listed here too, they might as well also be updated.

For changelogs of the packages involved, see the individual commit messages.

### CODE REVIEW

**Comment by Lyoness** [comment]
Hi @edmorley  I've merged your fork onto this branch to trigger packer builds
https://github.com/travis-ci/travis-cookbooks/tree/cha-edmorley-version-updates

Let's see if these pass separately from the overrides that you're doing in trusty packer-templates attributes.

**Comment by Lyoness** [comment]
All trusty packer images passed building from these changes :white_check_mark: 

[Amethyst](https://travis-ci.org/travis-infrastructure/packer-build/builds/268363778)
[Connie](https://travis-ci.org/travis-infrastructure/packer-build/builds/268363792)
[Garnet](https://travis-ci.org/travis-infrastructure/packer-build/builds/268363934)
[Sugilite](https://travis-ci.org/travis-infrastructure/packer-build/builds/268363948)

**Comment by Lyoness** [comment]
Node is the only thing that didn't propagate to the new dev images

https://travis-ci.org/Lyoness/travis_production_test/jobs/268396614#L546

But this is going to be taken care of in 
https://github.com/travis-ci/packer-templates/pull/494/files

**Comment by Lyoness** [comment]
Thanks @edmorley :yellow_heart:

**Comment by edmorley** [comment]
Many thanks for running those test builds. If there's a way I'm able to run them myself let me know so I can save you the hassle another time :-)

**Comment by meatballhat** [comment]
@edmorley We tend to kick them off via the packer-templates repo, which assumes (wildly!) that any travis-cookbooks PR may be tested by branch name alone, so to test *this* branch on the same stacks as listed (if it were present on this repository instead of your fork), for example:

``` bash
bundle exec bin/packer-build-cookbooks-branch \
    version-updates \
    ci-amethyst.yml ci-connie.yml ci-garnet.yml ci-sugilite.yml
```

**Comment by edmorley** [comment]
Ah GitHub creates hidden branches that map to open PRs, so I think this PR would be available on this repo as a branch named `pull/889/head` - perhaps that would save having to copy the fork branch to this repo?

**Comment by meatballhat** [comment]
@edmorley Please feel free to push branches to this repo, too! 😃

**Comment by edmorley** [comment]
Oh yes I forgot I could!

**Comment by edmorley** [comment]
> so I think this PR would be available on this repo as a branch named pull/889/head - perhaps that would save having to copy the fork branch to this repo?

I tried this but the script didn't like it. For future PRs I'll just use branches on the upstream repo instead.

**Pull request merged**
