### PR TITLE
Update Maven

### PR DESCRIPTION
**Pull request by ctubbsii**
Updates maven 3 to latest version of maven which still builds against JDK < 1.7 (3.2.5) without toolchains.
Updates maven central mirror to use HTTPS/TLS

### CODE REVIEW

**Comment by meatballhat** [comment]
@ctubbsii I started down the path of resolving the conflicts before I realized this change is on an upstream cookbook.  Was the upstream cookbook already updated, do you know?  If so, then the right thing for us to do here is to re-vendor the latest version, which hopefully also includes a bump in the metadata version.

**Comment by ctubbsii** [comment]
@meatballhat I'm not really sure I understand the "upstream cookbook" you're referring to.

**Comment by meatballhat** [comment]
@ctubbsii Any of the cookbooks in `./community-cookbooks` are vendored, meaning that updates should not be made in the travis-cookbooks repository, but instead at the source of truth.  Does that make more sense? 😺

**Comment by ctubbsii** [comment]
@meatballhat I guess that makes sense. From a source-control/GitHub repo/contributor perspective, it's not obvious that the source for the cookbooks in this repo have an upstream source.

**Comment by meatballhat** [comment]
@ctubbsii You're absolutely right that it isn't as obvious as it could be, although it's not for lack of trying. The top level README mentions that the `./community-cookbooks` tree contains vendored stuff, and there is a [README inside the relevant path](../tree/master/community-cookbooks/README.md).  Outside of documentation and noticing changed files in PRs, I suppose we could take advantage of github issue templates (?)

**Comment by meatballhat** [comment]
@ctubbsii I'm going to close this out for now, but please yell if you disagree.

**Pull request closed without merging**
