### PR TITLE
Updated PHP

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
@BanzaiMan Can this make it into 2015-06-29?

**Comment by BanzaiMan** [comment]
Unfortunately, we face some technical issues that prevent us from conducting build environment updates.

**Comment by GrahamCampbell** [comment]
Ok. :)

**Comment by meatballhat** [comment]
@GrahamCampbell oh no!

**Comment by GrahamCampbell** [comment]
Going to send a new PR.

**Pull request closed without merging**
