### PR TITLE
Cleanup & reducing defaults for travis_perlbrew cookbook

### PR DESCRIPTION
**Pull request by meatballhat**

### CODE REVIEW

**Comment by kentfredric** [comment]
What's the motivation for this change? To the perl toolchain people, this reduction of testing targets is a serious step backwards IMO.

**Comment by Grinnz** [comment]
Agreed, testing on several perls is the primary reason I use Travis.

**Comment by meatballhat** [comment]
@kentfredric @Grinnz sorry about the confusion.  This change is to the cookbook default attributes, which does not have a direct relationship to what is baked into each image.  The `master` branch of this repo (currently) only applies to the [trusty beta](http://docs.travis-ci.com/user/trusty-ci-environment/), for which Perl isn't yet supported.  I'm working with other team members and @ptc to get the Perl support in good shape.  Available versions may be found [over here in the packer-templates repo "travis_ci_mega" wrapper cookbook](https://github.com/travis-infrastructure/packer-templates/blob/75c843650c2688d297a65d5fc489a3c8f1623812/cookbooks/travis_ci_mega/attributes/default.rb#L22-L35).

**Comment by Grinnz** [comment]
thanks for the clarification!

**Comment by meatballhat** [comment]
@Grinnz thanks for your patience!

**Pull request merged**
