### PR TITLE
Update Docker to 17.04.0-ce and Compose to 1.12.0

### PR DESCRIPTION
**Pull request by tianon**
:tada: :+1:

### CODE REVIEW

**Comment by tianon** [comment]
It's probably worth discussing whether to update to 17.03 or 17.04 (ie, "stable" or "edge") -- I'm happy to update if there's a preference to go with one or the other. :+1:

(and will look into the Travis failure in a minute, if someone else doesn't beat me to it :innocent:)

**Comment by tianon** [comment]
The logs have a lot of things like the following in them, which doesn't _seem_ like something I've caused, but I might be misreading: :disappointed:
```
FC066: Ensure chef_version is set in metadata: cookbooks/travis_build_environment/metadata.rb:1
FC067: Ensure at least one platform supported in metadata: cookbooks/travis_build_environment/metadata.rb:1
```

**Comment by tianon** [comment]
So, since I made this, Docker's released 17.05.0, and 17.06.0 is coming next month.

This should either be pushed down to the stable channel (17.03.1) or up to the edge channel latest (17.05.0).  My own preference would be the stable channel, given that it has a three month bugfixes, etc support window, but I'm happy to update either way.  Here's an updated proposal that I'm happy to commit for testing, review, etc: (which also includes the download.docker.com switch)
```diff
diff --git a/cookbooks/travis_docker/attributes/default.rb b/cookbooks/travis_docker/attributes/default.rb
index 39e3799..f15c657 100644
--- a/cookbooks/travis_docker/attributes/default.rb
+++ b/cookbooks/travis_docker/attributes/default.rb
@@ -1,11 +1,11 @@
-default['travis_docker']['version'] = '17.04.0~ce-0~ubuntu-trusty'
+default['travis_docker']['version'] = '17.03.1~ce-0~ubuntu-trusty'
 default['travis_docker']['users'] = %w(travis)
-default['travis_docker']['compose']['url'] = 'https://github.com/docker/compose/releases/download/1.12.0/docker-compose-Linux-x86_64'
-default['travis_docker']['compose']['sha256sum'] = '6f7d649763318974684e32861249795f23e29b67226e034107dd0e25525d8af3'
+default['travis_docker']['compose']['url'] = 'https://github.com/docker/compose/releases/download/1.13.0/docker-compose-Linux-x86_64'
+default['travis_docker']['compose']['sha256sum'] = '0d8af4d3336b0b41361c06ff213be5c42e2247beb746dbc597803e862af127e8'
 default['travis_docker']['update_grub'] = true
-default['travis_docker']['binary']['url'] = 'https://get.docker.com/builds/Linux/x86_64/docker-17.04.0-ce.tgz'
-default['travis_docker']['binary']['version'] = '17.04.0-ce'
-default['travis_docker']['binary']['checksum'] = 'c52cff62c4368a978b52e3d03819054d87bcd00d15514934ce2e0e09b99dd100'
+default['travis_docker']['binary']['url'] = 'https://download.docker.com/linux/static/stable/x86_64/docker-17.03.1-ce.tgz'
+default['travis_docker']['binary']['version'] = '17.03.1-ce'
+default['travis_docker']['binary']['checksum'] = '3e070e7b34e99cf631f44d0ff5cf9a127c0b8af5c53dfc3e1fce4f9615fbf603'
 default['travis_docker']['binary']['binaries'] = %w(
   docker
   docker-containerd
diff --git a/cookbooks/travis_docker/recipes/package.rb b/cookbooks/travis_docker/recipes/package.rb
index 4b27517..f569c25 100644
--- a/cookbooks/travis_docker/recipes/package.rb
+++ b/cookbooks/travis_docker/recipes/package.rb
@@ -21,10 +21,10 @@
 # THE SOFTWARE.
 
 apt_repository 'docker' do
-  uri 'https://apt.dockerproject.org/repo'
-  distribution 'ubuntu-trusty'
-  components ['main']
-  key 'https://apt.dockerproject.org/gpg'
+  uri 'https://download.docker.com/linux/ubuntu'
+  distribution 'trusty'
+  components ['stable', 'edge']
+  key 'https://download.docker.com/linux/ubuntu/gpg'
   retries 2
   retry_delay 30
   action :add
```

**Comment by meatballhat** [comment]
@tianon I like it!  `git apply <comment`

**Comment by tianon** [comment]
Updated! :heart:

**Comment by edmorley** [comment]
@meatballhat, Hi! Do you have a rough timeline for when this might be deployed? :-)

We're just trying to work out whether recent changes to the docs (that made them reference `docker-ce` already) should be reverted so the instructions still work (travis-ci/docs-travis-ci-com#1258).

**Comment by Lyoness** [comment]
Hi @edmorley.  These docker images are already available tagged `group: edge` for our docker service in a full VM, and will undergo one more week of testing by QA and the community.

  All docker images are being updated in 6 days, on Wednesday, June 21st.

**Comment by edmorley** [comment]
Thank you for the reply! 

I tried this out using `group: edge`, but was initially confused that the Docker/Compose versions didn't match those in the PR title. I now see that the PR changed after opening - I don't suppose you could update the PR title? :-)

**Pull request merged**
