### PR TITLE
Update Gradle from v4.10.2 to v5.1.1

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@joepvd I saw your merge commit to update with master branch, I can also do a rebase with it, please let me know if there is anything need me to do, thanks ;)

**Comment by joshk** [comment]
thank you for the contribution, once this passes I'll merge it in

please keep the PRs coming :)

**Comment by PeterDaveHello** [comment]
Sure thing!

**Comment by PeterDaveHello** [comment]
@joshk is this something you can also help review with https://github.com/travis-ci/apt-source-safelist/pull/403? Thanks.

**Pull request merged**
