### PR TITLE
Update nvm to v0.33.4

### PR DESCRIPTION
**Pull request by ljharb**
Updates nvm to v0.33.4.

Is this something that could be done automatically? Or will I always have to come here and file this PR with every release?

### CODE REVIEW

**Comment by BanzaiMan** [comment]
`nvm` is updated to the latest release automatically when `travis-build` is deployed.

**Comment by meatballhat** [comment]
@ljharb yep, like @BanzaiMan said, I don't think new PRs are necessary for each release 👍

**Comment by edmorley** [comment]
For anyone else who was curious, nvm/nvm-exec are fetched as a rake task during travis-build deploy here:
https://github.com/travis-ci/travis-build/blob/024b16211070bdbeb98b32e6bed9a3fd03be1fe2/lib/travis/build/rake_tasks.rb#L189-L199

And then the nodejs travis-build script fetches those cached versions at runtime, here:
https://github.com/travis-ci/travis-build/blob/024b16211070bdbeb98b32e6bed9a3fd03be1fe2/lib/travis/build/script/node_js.rb#L147-L156

**Comment by ljharb** [comment]
Ahhh ok, how often is travis-build deployed? Is there an easy way I can request that?

It'd be really cool if when I release a new nvm version it could automatically start being used on travis :-)

**Pull request merged**
