### PR TITLE
Update ShellCheck from v0.6.0 to v0.7.0

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Ref: https://github.com/koalaman/shellcheck/releases/tag/v0.7.0

### CODE REVIEW

**Comment by ljharb** [comment]
Looks like there might be rubocop failures on master that need fixing first.

**Comment by PeterDaveHello** [comment]
hmmm, I'm not sure if those errors are related to the changes here :thinking:

**Comment by ljharb** [comment]
They’re not; they’re from a dep update, but looks like #1069 can address it.

**Comment by ljharb** [comment]
@PeterDaveHello please rebase this and it should pass

**Comment by PeterDaveHello** [comment]
Sure, thanks.

**Pull request merged**
