### PR TITLE
Update Lein Version

### PR DESCRIPTION
**Pull request by SevereOverfl0w**
Updates Leiningen version to latest, which allows for some major changes to be runnable again.

Solves:
https://github.com/travis-ci/travis-ci/issues/4791
https://github.com/travis-ci/travis-ci/issues/5025 (partially)

### CODE REVIEW

**Comment by meatballhat** [comment]
@SevereOverfl0w thanks for the contribution!  The `./community-cookbooks` tree contains vendored upstream cookbooks.  If there's a new `lein` cookbook version available, then re-vendoring is the preferred method of update.  If there *is not* a new `lein` cookbook available with this attribute update, pretty please take it up with the upstream and then ping us when it's ready :heart_eyes_cat:

**Comment by SevereOverfl0w** [comment]
https://github.com/michaelklishin/leiningen-chef-cookbook/pull/1

Upstream were notified back in November. Unfortunately leiningen 2.5.1 has a significant bug with a feature of clojure (Reader conditionals) which makes using Travis CI difficult.

**Comment by belucid** [comment]
@meatballhat seems michaelklishin/leiningen-chef-cookbook#1 was merged.

**Comment by meatballhat** [comment]
@belucid :+1: :grin:

**Comment by meatballhat** [comment]
Superseded by https://github.com/travis-ci/travis-cookbooks/pull/663

**Pull request closed without merging**
