### PR TITLE
Update `nvm` to `v0.31.6`

### PR DESCRIPTION
**Pull request by ljharb**
This includes LTS support.

### CODE REVIEW

**Comment by ljharb** [comment]
For posterity: this is for the image; https://github.com/travis-ci/travis-build/pull/821 is for the on-the-fly updating.

**Comment by ljharb** [comment]
@BanzaiMan ping :-)

**Comment by meatballhat** [comment]
😆

**Comment by meatballhat** [comment]
@ljharb Can you get up to date with `master` pretty please?  I promise I won't move `HEAD` again :grin:  (for .... at least a few hours... )

**Comment by ljharb** [comment]
I'm always happy to rebase :-)

**Comment by ljharb** [comment]
@meatballhat thanks! rebased, tested, merged.

**Pull request merged**
