### PR TITLE
Update ShellCheck from v0.4.7 to v0.5.0

### PR DESCRIPTION
**Pull request by PeterDaveHello**
ShellCheck v0.5.0 just released
 - https://github.com/koalaman/shellcheck/releases/tag/v0.5.0

### CODE REVIEW

**Comment by ljharb** [comment]
I'm waiting on https://github.com/Homebrew/homebrew-core/pull/28544 before merging this, fwiw.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/28544 shipped.

**Comment by PeterDaveHello** [comment]
Looks like even the latest Xenial environment on Travis CI, which was just released few days ago, is still using ShellCheck v0.4.7 ...

**Comment by joepvd** [comment]
Can you show a link to a build log where you have seen shellcheck to be of version 0.4.7 on xenial?

**Comment by PeterDaveHello** [comment]
@joepvd sure:
https://travis-ci.org/PeterDaveHello/ColorEchoForShell/jobs/454409270

**Comment by PeterDaveHello** [comment]
Looks good with that: https://travis-ci.org/PeterDaveHello/ColorEchoForShell/jobs/454963203, any idea?

**Comment by joepvd** [comment]
The `generic` language tag was not available on xenial, except for on an ancient image. This is being addressed with https://github.com/travis-ci/packer-templates/pull/658.

After being merged, this will be available on the stable images after they have been re-tagged.

Thanks for reporting :)

**Comment by PeterDaveHello** [comment]
Thank you @joepvd!
BTW, the ancient image you mentioned, seem to be unreliable, failed by accident at a very high rate, however, the new minimal image looks fine :+1:

**Pull request merged**
