### PR TITLE
Add ssl cert/key and travis_ssl user to mysql environment

### PR DESCRIPTION
**Pull request by grooverdan**
Closes travis/travis-ci#4808

rough prototype - https://travis-ci.org/grooverdan/travis-db-ssl-test and https://github.com/grooverdan/travis-db-ssl-test to show it works.

If you don't trust the cert/keys I've got. delete them, install gnutls-bin and run make.

### CODE REVIEW

**Comment by meatballhat** [comment]
@grooverdan I've just gone through the process of updating `master` to use unaltered upstream cookbooks, so this change can/should either be added upstream or to a custom Travis-specific cookbook, e.g. `cookbooks/travis_mysql`.  Thank you!

**Comment by meatballhat** [comment]
@grooverdan also worth mentioning is that the `master` branch will not apply to images based on Ubuntu 12.04 (for which the `precise-stable` branch exists)

**Comment by grooverdan** [comment]
ack. thanks for the info.

**Comment by meatballhat** [comment]
@grooverdan And another, sorry! 💖   Please target the `precise-stable` branch if desired!

**Comment by grooverdan** [comment]
For the next person who cares about this feature - current area look is cookbooks/travis_build_environment/recipes/mysql.rb. Where it gets to before someone looks at it, who knows.

**Pull request closed without merging**
