### PR TITLE
[12.04] Updated PHP

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I'm not really sure what's going on with php on the master branch?

**Comment by meatballhat** [comment]
@GrahamCampbell perhaps the biggest difference is that the default attributes in the cookbooks on the `master` branch should not be considered equivalent to what is used when building images.  The `travis_ci_mega` wrapper cookbook over in the [packer templates repo](https://github.com/travis-infrastructure/packer-templates) sets a bunch of attributes at the `override` level that are authoritative.

**Comment by GrahamCampbell** [comment]
Ok. :)

**Comment by meatballhat** [comment]
@GrahamCampbell Sorry about the bump.  Are you able to re-integrate `precise-stable`?

**Comment by GrahamCampbell** [comment]
> Are you able to re-integrate precise-stable?

Not quite sure what you mean? I've rebased?

**Comment by GrahamCampbell** [comment]
Tests green now.

**Comment by meatballhat** [comment]
@GrahamCampbell once more?  Sorry again.  I didn't anticipate how the github protected branches plays across forks what with the lack of "Update now" button.

**Comment by GrahamCampbell** [comment]
There is an update now button on my end. ;)

**Pull request closed without merging**
