### PR TITLE
Add GHC 7.10.2 to haskell environment

### PR DESCRIPTION
**Pull request by DanielG**
GHC 7.10 has been released for quite a while now and with the new container based infrastructure we can't use the apt repositories that existed for this previously anymore so it would be nice to have 7.10 in the standard haskell environment.

Thanks

### CODE REVIEW

**Comment by lierdakil** [comment]
:+1: for inclusion ASAP, this could make life that much easier.

**Comment by rtfeldman** [comment]
+1 - this is definitely a blocker for us

**Comment by alexkalderimis** [comment]
:+1:  This would be really great guys

**Comment by iphydf** [comment]
This can now be 7.10.3.

**Comment by meatballhat** [comment]
Sorry to let this languish for so long.  I changed some structural stuff in the repo layout that makes this patch invalid, but I'm also working on some Haskell changes for an upcoming update to Ubuntu Trusty environments in #798

**Pull request closed without merging**
