### PR TITLE
Add PostgreSQL 9.4 to master branch

### PR DESCRIPTION
**Pull request by gildegoma**
@BanzaiMan can you please double check if the second commit (836a3fa) is required (or at least preferred). It comes from c32c91d2ebbca08a3c309de7a7bb34d87b7cb8b8 on the trusty branch.

Resolve https://github.com/travis-ci/travis-ci/issues/2983

About Quality Assurance:
* [x] everything installs smoothly on precise64 and trusty64
* [x] do some verifications about PostGIS and other addons (not done yet)

### CODE REVIEW

**Comment by BanzaiMan** [comment]
`changes.md` needs conflict resolution, since I merged another PR).

**Comment by gildegoma** [comment]
@BanzaiMan force rebased against master to fix the conflict. 

I also verified that the PostGIS (related) stuff correctly loads with 9.4:

```SQL
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION fuzzystrmatch;
CREATE EXTENSION postgis_tiger_geocoder;
SELECT PostGIS_version();
SELECT PostGIS_full_version();


            postgis_version            
---------------------------------------
 2.1 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

          postgis_full_version                                                                          
---------------------------------------
 POSTGIS="2.1.5 r13152"
GEOS="3.3.8-CAPI-1.7.8"
PROJ="Rel. 4.8.0, 6 March 2012"
GDAL="GDAL 1.9.2, released 2012/10/08"
LIBXML="2.7.8"
LIBJSON="UNKNOWN"
TOPOLOGY
RASTER
```

**Comment by gildegoma** [comment]
@BanzaiMan Last question before you merge:

> can you please double check if the second commit (836a3fa) is required (or at least preferred). It comes from c32c91d on the trusty branch.

**Comment by BanzaiMan** [comment]
OK. @gildegoma I've added you to https://github.com/BanzaiMan/travis_staging_test, which can use the test image. You can add anything you want to https://github.com/BanzaiMan/travis_staging_test/blob/ff494dbe47d27fc40443033d021201bf0719f9ab/.travis.yml to test PostgreSQL 9.4.

**Comment by BanzaiMan** [comment]
I'll mark this as "experimental" on the announcement.

**Comment by gildegoma** [comment]
@BanzaiMan OK, sorry for the delay for the staging tests.

I'll track https://github.com/travis-ci/docs-travis-ci-com/pull/184 and give you more feedbacks there if needed.

**Comment by gildegoma** [comment]
I tried on staging this morning, but at the moment the current Ruby VM provides 9.1, 9.2 and 9.3, but not 9.4. See https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/403253.

**Comment by BanzaiMan** [comment]
Because the image doesn't have 9.4 installed. I'll create a new one in a few hours.

**Comment by BanzaiMan** [comment]
I've provisioned a new test Ruby image with PostgreSQL 9.4. I re-ran the above test: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/jobs/403257.

**Comment by gildegoma** [comment]
Thanks @BanzaiMan :heart: :arrow_right: :shipit: !!!

**Pull request merged**
