### PR TITLE
Configure php with --enable-debug

### PR DESCRIPTION
**Pull request by shouze**

### CODE REVIEW

**Comment by shouze** [comment]
related to https://github.com/travis-ci/travis-ci/issues/3101

**Comment by BanzaiMan** [comment]
I'm closing this one for now. The usefulness of `--enable-debug` flag is dubious at best, and the speed implication is not negligible.

**Comment by shouze** [comment]
@BanzaiMan as a pro feature only - can you make it possible to launch debug workers with some ssh access in a near future ? Some other ci bring this kind of commodity, like scrutinizer-ci for example. It's not something we need all the time but it's very handy as sometimes it remains hard to reproduce some ci only segfaults.

**Comment by BanzaiMan** [comment]
Indeed, an easier access to debug VMs is on our roadmap. I am sorry that this is such a hassle right now.

**Pull request closed without merging**
