### PR TITLE
Conditionally disable ipv6, default true

### PR DESCRIPTION
**Pull request by meatballhat**
and omit ipv6 addresses in /etc/hosts, too

### CODE REVIEW

**Comment by allenluce** [comment]
Despite not having `sysctl_disable_ipv6` set to false (that I know of), my precise builds starting picking up this stuff about the time this was merged.

**Comment by allenluce** [comment]
(resulting in build failures as the Aerospike Go client failed to deal with `localhost` resolving to link-local IPv6 addresses)

**Comment by solarce** [comment]
@allenluce a recent change to the upstream Ubuntu GCE images has resulted in IPv6 now being **enabled** in our latest Trusty and Precise images, we are working to **disable** it, as it being enabled is causing various issues. Could you share a link to one of the failed builds please?

**Comment by allenluce** [comment]
Yup, please check out https://travis-ci.com/allenluce/receiver/builds/29672469

**Comment by solarce** [comment]
@allenluce we pushed a fix for this in our image update on Aug 11. How are things looking for you now?

**Comment by allenluce** [comment]
Yup, looks like it's working.  Thanks!

**Pull request merged**
