### PR TITLE
Update packagecloud community cookbook

### PR DESCRIPTION
**Pull request by joepvd**
With the current version of the packagecloud cookbook, repository specific gpg keys are not supported. Support for that was added since v0.2.0. This should address [the following error](https://travis-ci.org/travis-infrastructure/packer-build/jobs/476734838#L1215-L1228) in the builds for the `git-lfs`-package:

```
The following NEW packages will be installed:
git-lfs
0 upgraded, 1 newly installed, 0 to remove and 14 not upgraded.
Need to get 4931 kB of archives.
After this operation, 12.3 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
git-lfs
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
```

With this change, repository specific gpg keys should be fetched instead.

### CODE REVIEW

**Comment by MarkCallow** [comment]
I just removed my manual install of the key for git-lfs and I still get this error. Looks like this PR has not fixed the problem, unless it has not yet made it into production.

**Comment by joepvd** [comment]
Can you post a link to a build log, please?

**Comment by MarkCallow** [comment]
> Can you post a link to a build log, please?

https://travis-ci.org/MarkCallow/KTX-Software/jobs/481750195

**Comment by joepvd** [comment]
Could you try again after dropping `group: edge` from the config in `.travis.yml`?

**Comment by MarkCallow** [comment]
That worked. Thanks.

I think I put `group: edge` in to get early access to Xenial. Obviously not needed now.

**Pull request merged**
