### PR TITLE
Revert "Remove `./node_modules/bin` from `$PATH`"

### PR DESCRIPTION
**Pull request by BanzaiMan**
Reverts travis-ci/travis-cookbooks#786

### CODE REVIEW

**Comment by ljharb** [comment]
Why?

**Comment by ljharb** [comment]
Anyone who this breaks is probably broken locally too.

**Comment by BanzaiMan** [comment]
Hello. There are many repositories at this time relying on this component being on `$PATH`. If we are to re-introduce it, it is best to give more advance warning.

**Comment by ljharb** [comment]
Ok - what's the plan to do that? The sooner repos can't rely on this misfeature, the better.

**Comment by BanzaiMan** [comment]
We'll deal with Node.js (and potentially other languages) `$PATH` with `travis-build`.

**Comment by ljharb** [comment]
Will the removal now be permanent?

**Pull request closed without merging**
