### PR TITLE
Changes in support of "minimal" trusty image

### PR DESCRIPTION
**Pull request by meatballhat**
* [x] make sure precise image(s) still build correctly

### CODE REVIEW

**Comment by BanzaiMan** [comment]
It is missing `jdk_switcher`. See HS 16762.

**Comment by meatballhat** [comment]
@BanzaiMan I don't understand how your statement is related to this PR, as the run lists for the trusty minimal image and future images are managed in https://github.com/travis-infrastructure/packer-templates/ :confused:

**Comment by BanzaiMan** [comment]
@meatballhat Sorry for the confusion. I tracked the support ticket to this branch based on a guess. I am looking for whatever the solution is to add `jdk_switcher` to the Trusty image. The process was a complete mystery to me.

**Comment by meatballhat** [comment]
I'm sorry to hear that I've caused a mystery.  I've been communicating about the packer-templates repository to various team members, but haven't talked directly with you.  This comment belongs over there IMHO.

**Pull request merged**
