### PR TITLE
add builds for perl 5.22, removing 5.21

### PR DESCRIPTION
**Pull request by haarg**
There aren't any 5.23 releases yet, so not adding any dev release builds
currently.

### CODE REVIEW

**Comment by karenetheridge** [comment]
+1

**Comment by masiuchi** [comment]
+1

**Comment by BanzaiMan** [comment]
I am down for merging this. However, I'd probably remove 5.18-extras, since the `extras` aren't getting used, and 5.18 is now 2 stable versions old.

**Comment by karenetheridge** [comment]
@BanzaiMan In the Perl-Toolchain-Gang, we support back to perl 5.8, so all the old versions (with threaded variants) are still valuable and used.

**Comment by BanzaiMan** [comment]
The current problem with Perl (and Ruby, Python, and most PHP versions) runtimes is that they are compiled from source at image provision time, and keeping old versions cost time as well as disk space.

**Comment by haarg** [comment]
I've added a commit to remove 5.18-extras.

**Comment by dagolden** [comment]
+1

Could this please get merged soon?

**Comment by BanzaiMan** [comment]
Note that we do not have concrete plans to update build environments yet. Until we roll out the update, 5.22 is not available.

**Comment by wbraswell** [comment]
@BanzaiMan 
Can I somehow use this to enable Perl v5.22 testing in a normal Travis setup?

My .travis.yml file:

https://github.com/wbraswell/rperl/blob/master/.travis.yml

My Travis landing page:

https://travis-ci.org/wbraswell/rperl

Thanks!
~ Will

**Comment by BanzaiMan** [comment]
@wbraswell Sorry, but it is not possible at the moment. I am working on some on-the-fly installation process to the ease the pain, but it might be a few days before that's possible.

**Comment by wbraswell** [comment]
@BanzaiMan 
Thanks so much!
I've got quite a few people sending me personal bug reports on Perl v5.22 but I can't replicate anything on Travis...
I look forward to your pending solution.

**Comment by wbraswell** [comment]
@BanzaiMan 
Any update here?

**Comment by tokuhirom** [comment]
@BanzaiMan ping?

**Comment by glensc** [comment]
i wonder why specifying 5.22 in .travis.yml file does not yeild an error, but rather continues with 5.14 version.

i did not realize 5.22 was missing until i started to investigate some error.

cut from build log:
```
$ perlbrew use 5.22
ERROR: The installation "5.22" is unknown.
$ perl --version
This is perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-gnu-thread-multi
(with 57 registered patches, see perl -V for more detail)
```

as you can see, it continued with next command (`perl --version`)

**Comment by BanzaiMan** [comment]
Sorry for the delay. The on-demand installation is dealt with by https://github.com/travis-ci/travis-build/pull/518, but it needs some extra work.

Conceptually, that we continue with the default version when you specify a bad version is a separate issue. Please open an issue with https://github.com/travis-ci/travis-ci/issues/new.

**Comment by wbraswell** [comment]
So does Travis support Perl v5.22 yet or not?!?

**Comment by BanzaiMan** [comment]
@wbraswell Not yet.

**Comment by Tux** [comment]
Then why is the issue closed?
Most of the perl developers that use Travis would love to see 5.21 replaced with both 5.22 and 5.23 testing abilities.

**Comment by BanzaiMan** [comment]
This issue is for cookbooks.

**Pull request merged**
