### PR TITLE
Pin rabbitmq-server to the last 3.6.x release

### LINKED ISSUE #953: Builds broken by the newly released rabbitmq-server 3.7.0
In the last couple of hours rabbitmq-server 3.7.0 was published to the packagecloud repo, replacing the previous 3.6.14 release:
https://packagecloud.io/rabbitmq/rabbitmq-server

Unfortunately this has broken the Garnet/Amethyst/Opal/Sardonyx builds:
https://travis-ci.org/travis-infrastructure/packer-build/jobs/309156764#L2760

...since rabbitmq-server 3.7+ has raised the minimum required Erlang/OTP version to 19.3+:
https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.0-rc.2
https://www.rabbitmq.com/which-erlang.html

...and the stock Ubuntu erlang packages are much older:
* Trusty: 16.b.3 ([build log](https://travis-ci.org/travis-infrastructure/packer-build/jobs/308750635#L5848); [ubuntu package listing](https://packages.ubuntu.com/trusty-updates/erlang))
* Xenial: 18.3 ([build log](https://travis-ci.org/travis-infrastructure/packer-build/jobs/308627553#L5775); [ubuntu package listing](https://packages.ubuntu.com/xenial/erlang))

I think the best fix for now is just to pin the rabbitmq-server version to 3.6.14 and worry about upgrading system Erlang/OTP (and handling any other rabbitmq-server 3.7 breaking changes) later.

I'll open a PR.

### PR DESCRIPTION
**Pull request by edmorley**
To fix build breakage caused by the recent 3.7.0 release, which raised the minimum Erlang/OTP version to one that is newer than the stock Ubuntu package. This pins the version to the same one that was used until yesterday.

Short term this approach seems preferable to (a) trying to figure out which upstream OTP APT repository to use instead of the stock Ubuntu repo, (b) likely dealing with more fallout from other OTP and rabbitmq-server breaking changes.

Fixes #953.

Edit:  I've added a commit to suppress Foodcritic FC104 and FC109 to green up master (see #955 - the cleanup can be handled there later).

Test builds to follow.

### CODE REVIEW

**Comment by meatballhat** [comment]
@edmorley Thank you so much! 💖

**Comment by edmorley** [comment]
No problem :-)

Test garnet build in progress here:
https://travis-ci.org/travis-infrastructure/packer-build/builds/309549146

**Comment by edmorley** [comment]
The docker build succeeded:
https://travis-ci.org/travis-infrastructure/packer-build/jobs/309565975

However the GCE build failed during HHVM APT repo setup with `gpgkeys: key 5A16E7281BE7A449 can't be retrieved`:
https://travis-ci.org/travis-infrastructure/packer-build/jobs/309565974#L1920

I'm presuming the HHVM error is either an existing intermittent failure, or else new breakage due to upstream HHVM changes that will need to be worked around in another PR. If so, then it seems reasonable to merge this Pr for now anyway.

@meatballhat sound good to you?

**Comment by meatballhat** [comment]
@edmorley good enough for me!

**Comment by edmorley** [comment]
The latest builds on master (thank you for triggering them) have all passed:
* [connie](https://travis-ci.org/travis-infrastructure/packer-build/builds/309642319): ✅ 
* [amethyst](https://travis-ci.org/travis-infrastructure/packer-build/builds/309642338): ✅ 
* [garnet](https://travis-ci.org/travis-infrastructure/packer-build/builds/309642327): ✅

**Pull request merged**
